sudo: true
language: node_js
node_js:
  - 6
os:
  - linux
#  - osx
env:
  - RELEASE_OSX=0
addons:
  apt:
    packages:
      - xvfb                # Dependency for headless testing via virtual frame buffer
before_install:
  - npm i -g npm@5.1.0
  - npm --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/innosetup/setup.sh; fi
install:
  - export DISPLAY=':99.0'  # https://electron.atom.io/docs/tutorial/testing-on-headless-ci/
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & # Create a virtual display
  - npm i
  - npm i -g jest codecov
  - npm dedupe
  - npm run load-apps
before_script:
  - gulp crowdin # always sync locale
script:
  - ./scripts/travis_tests.sh
before_deploy:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH" =~ ^release-.*$ ]]; then
      RELEASE_OSX=1;
      echo 'TODO: release compressed DMG';
    fi
  - ./scripts/bundle_binaries.sh ./release ./release/tagged
deploy:
# global overview page
- provider: surge
  project: "./scripts/releases/overview"
  skip_cleanup: true
  on:
    all_branches: true

# develop branch
- provider: surge
  project: "./release/overview"
  domain: tc-develop.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    branch: develop

- provider: surge
  project: "./release/linux-x64"
  domain: linux.tc-develop.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    branch: develop

- provider: surge
  project: "./release/macos-x64"
  domain: macos.tc-develop.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    branch: develop

- provider: surge
  project: "./release/win-x64"
  domain: win64.tc-develop.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    branch: develop

- provider: surge
  project: "./release/win-x32"
  domain: win32.tc-develop.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    branch: develop

# sandbox branch
- provider: surge
  project: "./release/overview"
  domain: tc-sandbox.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^sandbox-.*$"

- provider: surge
  project: "./release/linux-x64"
  domain: linux.tc-sandbox.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^sandbox-.*$"

- provider: surge
  project: "./release/macos-x64"
  domain: macos.tc-sandbox.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^sandbox-.*$"

- provider: surge
  project: "./release/win-x64"
  domain: win64.tc-sandbox.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^sandbox-.*$"

- provider: surge
  project: "./release/win-x32"
  domain: win32.tc-sandbox.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^sandbox-.*$"
# release branch
- provider: surge
  project: "./release/overview"
  domain: tc-release.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^release-.*$"

- provider: surge
  project: "./release/linux-x64"
  domain: linux.tc-release.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^release-.*$"

- provider: surge
  project: "./release/macos-x64"
  domain: macos.tc-release.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: '$TRAVIS_BRANCH =~ ^release-.*$'

- provider: surge
  project: "./release/win-x64"
  domain: win64.tc-release.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^release-.*$"

- provider: surge
  project: "./release/win-x32"
  domain: win32.tc-release.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "$TRAVIS_BRANCH =~ ^release-.*$"

# release tag
- provider: releases
  name: $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  file_glob: true
  file: "./release/tagged/*"
  overwrite: true
  skip_cleanup: true
  prerelease: true
  draft: true
  on:
    tags: true
  api_key:
   secure: JfttyLVoBRJoRhZ2P+QSn02NJfB8e3nwlUBh0BBz8txdvfIHcZIie5eBIqKfU6ztEE3Sdg+8aSQWfgpODBGfiGpLNtOz2joPMjM+TxI1xIz/E7p7AGWIyQpozUObmvGkyjHGvQR79T0khervXIbF4faW+OmjxJtXe0eu5mk7ZAKVDc0Ek51ZnVgIpcK+U/0MpNq7pEGWHjbVhkD6ZrQPQURV/GNUhqhXSBiZoCmdUmwpQ5oJtIlBrhpqjtNhVL5z4gya9gRdsRmsf7CCIRaLDgA3jJmSAnK4uXJ3UX5Y/qKB/hPAzdci0QMwXIzeoWsVmw7R0mQrdD5D6Uy0I5rPR+351OQZi+9ECQynlvcl62Cy2BP3sY6ul3pyPpjZw/LTQg74StCEiZBABBYnu7OpRcAe26vs1YhqY0KHZvRO4+Mul4W10di/Bw7hKLoEu4CTWzgnBhgMMqoQZkDKPFp9Q/gIf7hGypVPeHkruoS+gMeRSzF2M7cD14Ct+MoeusGwimojtO0aAzJ4jScyvHzw/Y1zlgLBIMgZBrIxtyEC7lskVFQeAYcoKvvZQlMZyprxxnW4RdvH/r2Rx4XfIvQ2e/wVtgz/1YJd+g49kpYFUHsDi1fCAXs95P9Qlz/B0CyKYqCJVw7jwoU7zl4SHcYKjB3S26Jo5z0kyLA4ykyFCYo=
