sudo: true
language: node_js
node_js:
  - 6
os:
  - linux
addons:
  apt:
    packages:
      - xvfb                # Dependency for headless testing via virtual frame buffer
before_install:
  - npm i -g npm@5.1.0
  - npm --version
  - ./scripts/innosetup/setup.sh
install:
  - export DISPLAY=':99.0'  # https://electron.atom.io/docs/tutorial/testing-on-headless-ci/
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & # Create a virtual display
  - npm i
  - npm i -g jest coveralls codecov
  - npm dedupe
  - npm run load-apps
script:
  - eslint ./src && jest --coverage
  - cat ./coverage/lcov.info | coveralls
  - codecov
before_deploy: # we build one platform at a time to avoid timeouts
  - gulp build --win
  - gulp build --linux
  - gulp build --osx
  - gulp release
deploy:
# develop branch
- provider: surge
  project: "./release/"
  domain: tc-develop.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    branch: develop
    condition: "-d ./release"
# sandbox branch
- provider: surge
  project: "./release/"
  domain: tc-sandbox.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "-d ./release && $TRAVIS_BRANCH =~ ^sandbox-.*$"
# release branch
- provider: surge
  project: "./release/"
  domain: tc-release.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    condition: "-d ./release && $TRAVIS_BRANCH =~ ^release-.*$"
# release tag
  provider: releases
  name: $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  file_glob: true
  file: release/*
  overwrite: true
  skip_cleanup: true
  prerelease: true
  draft: true
  on:
    tags: true
  api_key:
   secure: JfttyLVoBRJoRhZ2P+QSn02NJfB8e3nwlUBh0BBz8txdvfIHcZIie5eBIqKfU6ztEE3Sdg+8aSQWfgpODBGfiGpLNtOz2joPMjM+TxI1xIz/E7p7AGWIyQpozUObmvGkyjHGvQR79T0khervXIbF4faW+OmjxJtXe0eu5mk7ZAKVDc0Ek51ZnVgIpcK+U/0MpNq7pEGWHjbVhkD6ZrQPQURV/GNUhqhXSBiZoCmdUmwpQ5oJtIlBrhpqjtNhVL5z4gya9gRdsRmsf7CCIRaLDgA3jJmSAnK4uXJ3UX5Y/qKB/hPAzdci0QMwXIzeoWsVmw7R0mQrdD5D6Uy0I5rPR+351OQZi+9ECQynlvcl62Cy2BP3sY6ul3pyPpjZw/LTQg74StCEiZBABBYnu7OpRcAe26vs1YhqY0KHZvRO4+Mul4W10di/Bw7hKLoEu4CTWzgnBhgMMqoQZkDKPFp9Q/gIf7hGypVPeHkruoS+gMeRSzF2M7cD14Ct+MoeusGwimojtO0aAzJ4jScyvHzw/Y1zlgLBIMgZBrIxtyEC7lskVFQeAYcoKvvZQlMZyprxxnW4RdvH/r2Rx4XfIvQ2e/wVtgz/1YJd+g49kpYFUHsDi1fCAXs95P9Qlz/B0CyKYqCJVw7jwoU7zl4SHcYKjB3S26Jo5z0kyLA4ykyFCYo=
