sudo: true
language: node_js
node_js:
  - 8.16.1
os:
  - linux
before_install:
  - npm i -g npm@6.4.1 jest codecov
  - npm --version
install:
  - npm ci
  - npm run load-apps
before_script:
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then npm run doc; fi
  - NODE_OPTIONS=--max-old-space-size=8192
script:
  - ./.concourse/test.sh
deploy:

# deploy documentation
- provider: surge
  project: "./docs/translationCore"
  domain: docs.tc.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    branch: develop
